### ISSUE TITLE
Download annotations in annotation demo

### ISSUE THREAD

**Issue by jordanhart** [WorkAroundOnline/react-image-annotate#4]
Hi! Would it be possible to include an example of how to download the annotations from the webpage. It would be great to be see a clear example on how to access the annotations, and download as a json.

Thanks!

**Comment by seveibar** [comment]
Hey @jordanhart,

If you hit "View Output" at the top you can see the output json. We can add download functionality. PRs welcome :)

**Comment by jordanhart** [comment]
Thanks!
